import { cn } from "@/utils/misc";
import "./globals.css";
import { Inter } from "next/font/google";
import Nav from "@/components/Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="">
      <body className={cn(inter.className, "dark:bg-slate-800")}>
        <Nav />
        {children}
      </body>
    </html>
  );
}
